### ISSUE TITLE
Properties status vs active in version 2.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#100]
papiNet should be consistent in the design of schemas.
Now two properties status and active are used to specify the same thing.

status:
     type: string
     enum:
        - Active
        - Inactive

active:
    type: boolean

**Comment by patricekrakow** [comment]
Yes, I think the property `active` (3 occurrences) should be replaced by the property `status` to be consistent.

**Comment by patricekrakow** [comment]
We decided to go with OPTION 2: `active: true` or `active: false`.

**Comment by patricekrakow** [comment]
Done, see commit [291c26a](https://github.com/papinet/papiNet-API/commit/291c26a5480c172d6302abd92b65e9d9b8076d26).
