### ISSUE TITLE
Property UOM in version 2.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#102]
papiNet has a rule that the property names should start with a lower case character.
The name of the property UOM starts with a upper case character.
The name should be changed to uOM.

**Comment by patricekrakow** [comment]
Strictly speaking, if you follow the lowerCamelCase, I think it shoud be `uom`. The full name would be `unitOfMeasure`.

The rules are: _"lowerCamelCase names capitalize the first letter of each word, except the first which is always lowercase, even if it's an acronym." (source: https://dart.dev/effective-dart/style)

**Comment by patricekrakow** [comment]
We decided to go for a strict lowerCamelCase.

**Comment by patricekrakow** [comment]
- `UOM` has been replaced by `uom`;
- `quantityUOM` has been replaced by `quantityUom`

in `papiNet-API.PROPOSAL.yaml`, see commit [342490a](https://github.com/papinet/papiNet-API/commit/342490aad16770d1b66f3ddf7f5da406aac95036).

Let's wait to finalized `papiNet-API.yaml` to close this issue.

**Comment by patricekrakow** [comment]
We closed this issue with @larsolofsson, @bengtwentus and @MrNordenberg.
