### ISSUE TITLE
partieIdentifier should be named partyIdentifier

### ISSUE THREAD

**Issue by globaltopmedia** [papinet/papiNet-API#103]
Small issue, it's partyIdentifier

https://github.com/papinet/papiNet-API/blob/aa915df241f1dba96a12d6dce4fc9cb33bc96b70/2.0.0/master-data.md?plain=1#L544

**Comment by patricekrakow** [comment]
Indeed, this is a typo. As it is just a documentation change, we can include it:

- silently in `2.0.0`
- explicitly in a new `2.0.1`
- only in `3.0.0` being our next release

**Comment by patricekrakow** [comment]
This change/patch is part of the commit [40a4306](https://github.com/papinet/papiNet-API/commit/40a43065b22d14d2f7587e134d27f67583789854). It will be merged with the branch supplier-order-3-0-0.
