### ISSUE TITLE
ListOfSupplierOrders: in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#105]
1.    numberOfLines:  name?
        numberOfLineItems is used in ver. 2.0.0. Naming should be consistent.
        Name a bit confusing because both PurchaseOrderNumber and SalesOrderNumber exist and line Items of salesOrder might  not be the same as for supplierOrder and purchaseOrder. Is it now clear that it is the numberOfLineItems of the supplierOrder only.
      
2.        numberOfLines: optional? numberOfLineItems is mandatory in ListPurchaseOrders

3.        supplierOrderStatus: optional? purchaseOrderStatus is required in ListPurchaseOrders

5.       salesOrderNumber: is on purchaseOrderLineItem in ver. 2.00
         Now in the header of the supplierOrder?

 6.      purchaseOrderNumber is assigned by the customer. Is it then OK having customerParty as optional?

**Comment by larsolofsson** [comment]
Decisions on 2023-12-20
1. numberOfLines to be change to numberOfLineItems.
2. numberOfLineItems should be changed to required.
3. supplierOrderStatus should be changed to required.
4. salesOrderNumber: should be move to the supplierOrderLineItem
5. Ok to have customerParty as optional.

**Comment by patricekrakow** [comment]
1. Done in commit [d12ef5a](https://github.com/papinet/papiNet-API/commit/d12ef5a7c4cc8219393a7c62d58c0bc1c9a9da83).
2. Done in commit [d12ef5a](https://github.com/papinet/papiNet-API/commit/d12ef5a7c4cc8219393a7c62d58c0bc1c9a9da83).
3. Done in commit [d12ef5a](https://github.com/papinet/papiNet-API/commit/d12ef5a7c4cc8219393a7c62d58c0bc1c9a9da83).
4. OK, that means that `salesOrderNumber` should be removed from `ListOfSupplierOrders` which contains only "header" information. Done in commit [d12ef5a](https://github.com/papinet/papiNet-API/commit/d12ef5a7c4cc8219393a7c62d58c0bc1c9a9da83).
What about the `purchaseOrderNumber`? Should it also be moved to the `supplierOrderLineItems` (in `GetSupplierOrderById`)?
5. No change.

**Comment by patricekrakow** [comment]
I should probably create a new issue to discuss further the remaining questions about the references to the _sales order(s)_ and the _purchase order(s)_ so we can close this issue with the commits containing all the changes we agreed on!

**Comment by patricekrakow** [comment]
Remaining actions/discussions are described in #121 and ...

**Comment by patricekrakow** [comment]
2024-01-17, finally we should leave the `purchaseOrderNumber` at the HEADER level and **remove** the `salesOrderNumber` completely!

**Comment by patricekrakow** [comment]
Done in commit [56a0b2b](https://github.com/papinet/papiNet-API/commit/56a0b2b382bf5a3b482018dde7cd3627a3c164dd).
