### ISSUE TITLE
GetSupplierOrderById: in ver. 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#106]
GetSupplierOrderById:

1.    supplierOrderStatus: Optional? Should be required
       purchaseOrderStatus is required in GetPurchaseOrderById:  ver 2.0.0

2.      salesOrderNumber: is on purchaseOrderLineIitem in ver.2.00
         Now in the header for the supplierOrder?

3.       confirmedShipToLocation:
         Property partyIdentifiers: should be change to property locationIdentifiers:, i.e. the same as in toLocation: and fromLocation:

4.      the same issue for locations regarding uuid in locationIdentifiers: as for partyIdentifiers:, issue #104

5.       modeType:
           The following enumerations can be removed for Paper and Pulp businesses:
           Air, Floating, Mail, OffRoad and Other.

 6.      unitType:
            The following enumerations can be removed for Paper and Pulp businesses:
            ForestryForwarderUnit, Wagon and Other.

**Comment by patricekrakow** [comment]
1. Done in commit [47ffffd](https://github.com/papinet/papiNet-API/commit/47ffffd27edce4fa3af56fd3f47c7cca13b3cc70).
2. Already done in commit [bcda087](https://github.com/papinet/papiNet-API/commit/bcda087c6ad13dfb34d90e47fe4d5f5386a351b0) according to issue #105.
3. Done in commit [47ffffd](https://github.com/papinet/papiNet-API/commit/47ffffd27edce4fa3af56fd3f47c7cca13b3cc70).
4. Corrected in commit [47ffffd](https://github.com/papinet/papiNet-API/commit/47ffffd27edce4fa3af56fd3f47c7cca13b3cc70).
5. Done in commit [47ffffd](https://github.com/papinet/papiNet-API/commit/47ffffd27edce4fa3af56fd3f47c7cca13b3cc70).
6. Done in commit [47ffffd](https://github.com/papinet/papiNet-API/commit/47ffffd27edce4fa3af56fd3f47c7cca13b3cc70).

**Comment by patricekrakow** [comment]
We closed this issue with @larsolofsson, @bengtwentus and @MrNordenberg.
