### ISSUE TITLE
sellerProduct: in ver. 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#107]
sellerProduct:

1.   brandName:, gradeCode: and gradeCodeName are assigned by the supplier/seller.  The customer can use a sellerproduct with these properties when ordering paper. So these properties are never assigned by the customer for a sellerProduct. So the assignedBy construct can be removed.

2. A sellerProduct can be fully-specified or not fully-specified. The identifier used for a not fully-specified sellerProduct is gradeCode in papiNet xml. The identifier used for a fully-specified sellerProduct is  partNumber in papiNet xml. 
I propose when having gradeCode that property partNumber: should be added. Property gradeCodename could be renamed to sellerProductName or productName, A choice could be added between gradeCode and partNumber (OneOf)

The customer can specify an customerArticle that can be can be fully-specified or not fully-specified. Properties brandName:, gradeCode: and partNumber: can also be used for a customerArticle. Property customerArticleName: or articleName: could be used for an customerArticle.

**Comment by larsolofsson** [comment]
Decisions on 2023-12-20
Current business cases for version 3.0.0 are without uuid and master data. Our decision is to currently remove the uuid from products, parties, locations and  customerArticles. 
Property partNumber should be added to sellerProduct and customerArticle.
gradeCodeName should be changed to productName.

**Comment by patricekrakow** [comment]
I think we need to (re)discuss the consequences of removing the (uu)id of parties and locations. How would we then present the links with the following (existing) API endpoints:
* `GET /parties/{partyId}
* `GET /locations/{locationId}

**Comment by patricekrakow** [comment]
@bengtwentus will prepare some proposals to be discussed...

**Comment by patricekrakow** [comment]
Let's summarize the needed changes for `sellerProduct` and `customerArticleReference`:

- `sellerProduct.id` ...
- `sellerProduct.brandName` ...
- `sellerProduct.gradeCode` ...
- `sellerProduct.gradeCodeName` ...
- `customerArticleReference.id`...
- `customerArticleReference.articleNumber` ...
- `customerArticleReference.articleName` ...

**Comment by patricekrakow** [comment]
When I will be ready with the commit, I will probably create a new issue to discuss further the overall usage of UUIDs so we can close this issue with the commit containing all the changes we agreed on!

**Comment by patricekrakow** [comment]
Changes done in commit [46c2cf1](https://github.com/papinet/papiNet-API/commit/46c2cf18782d116d9830dcc0bc5dfdce262e1798).

I will propose a JSON schema to:
- add the constraint that sellerProduct.gradeCode and sellerProduct.partNumber must not be both populated
- add the constraint that customerArticleReference.gradeCode and customerArticleReference.partNumber must not be both populated

within a the new issue ..., so we can already close this issue.

**Comment by patricekrakow** [comment]
The `minLength: 1` is missing with the `type: string` and the constraint must be explained in English prose within the `description `.

**Comment by patricekrakow** [comment]
The constraint `minLength: 1` has been added, see commit [38cbcd5](https://github.com/papinet/papiNet-API/commit/38cbcd571dd9b87c0abe0c7ce7a406b975365be8). Regarding the constraint, we will follow that up within issue #123.
