### ISSUE TITLE
customerArticleReference: in ver. 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#108]
customerArticleReference:

 A customerArticleReference will never be assigned by the supplier. The assignedBy construct can be removed. Properties of customerArticleReference could be brandName:, gradeCode:, partNumber: and customerArticleName or ArticleName, i.e. the same properties as in the customerArticle:

**Comment by larsolofsson** [comment]
Decisions on 2023-12-20
The assignedBy construct can be removed. Properties of customerArticleReference should be changed to brandName:, gradeCode:, partNumber: and ArticleName.

**Comment by patricekrakow** [comment]
This is a duplicate issue with issue #107.
