### ISSUE TITLE
Update of Notice.md

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#115]
The following text
_papiNet ® is a registered trademark of IDEAlliance on behalf of a global partnership between AF&PA, IDEAlliance, and papiNet GIE._

should be replaced by the text on papinet.org
_papiNet ® is a registered trademark of papiNet GIE._

Shouldn't all instances of "papiNet ®" be replaced by "papiNet®"?

**Comment by patricekrakow** [comment]
Agreed during papiNet CWG meeting, 2024-02-14 (Wed), and let's use "papiNet®" (without a blank).
