### ISSUE TITLE
Update of the file papinet-logo.jpg

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#116]
The file papinet-logo.jpg is missing the text "papiNet" or the text "papiNet® Powered" and should be updated.
Should it be the papiNet logo or the papiNet® Powered logo?
The file Notice.md is referring to the papiNet® Powered logo.

![image](https://github.com/papinet/papiNet-API/assets/63000261/f3b0c653-daca-4359-b95f-2a224bc8cf4e)

**Comment by patricekrakow** [comment]
I have the papiNet logo with the text "papiNet", but I don't have the papiNet logo with the text "papiNet® Powered".
But, let's first take a decision which one it should be...

**Comment by patricekrakow** [comment]
Done, see commit [729480b](https://github.com/papinet/papiNet-API/commit/729480b08434d727b72e8ed873744c42ff3fafa9).
