### ISSUE TITLE
Update of the file README.md, a typo.

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#118]
# papiNet API

[papiNet](http://www.papinet.org) is a global paper, forest products and bioproducts industry **e-Business initiative**, which has started in October 2000! papiNet consists of an **XML set of standard electronic documents** that facilitates the flow of information among parties engaged in buying, selling, and distribution of paper, forest and bio related products.

_Replace "has started in October 2000!" with "started in year 2000."_

**Comment by patricekrakow** [comment]
Done, see commit [4144e04](https://github.com/papinet/papiNet-API/commit/4144e04819dce865563ace16d8439213b6f1dde3).
