### ISSUE TITLE
Update of Voting Maintainers in the file MAINTAINERS.md

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#119]
**Voting Maintainers should be updated.**

Add Niklas Danell, Holmen
Should also Bo-Göran Skansen be added?

Remove Björn Jonsson Dannetun.

According to Governance:
Maintainers MUST remain active. If they are unresponsive for >6 months, they will be automatically removed unless a [two-thirds supermajority vote](https://en.wikipedia.org/wiki/Supermajority#Two-thirds_vote) of the other project maintainers agrees to extend the period to be greater than 6 months.

**Comment by patricekrakow** [comment]
I will add @PetterThy and @4boge as "Non-Voting Maintainer".
I will add Niklas Danell as a "Voting Maintainers" in replacement of @bjdannetun.

**Comment by patricekrakow** [comment]
Done, see commit [33d044c](https://github.com/papinet/papiNet-API/commit/33d044ce06f588d6b78b650baa54b5900bb8b3c9).
