### ISSUE TITLE
Update of the file CONTRIBUTING.md

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#120]
Now for 3 years, two headings are missing action texts.
**Let's Work on a New Feature**
**Let's Release a New Version of the papiNet API Standard**

Add action texts or remove the headings.

**Comment by patricekrakow** [comment]
Done, see commit [b89579e](https://github.com/papinet/papiNet-API/commit/b89579e67828de0194c5b7f64486f08aa3b47210).
