### ISSUE TITLE
Use `integer` type for `...LineItemNumber` properties in version 2.0.0 and 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#132]
Line Item Numbers in version 1.3.0 and papiNet XML is defined as 
          type: integer
          minimum: 0

In version 2.0.0 and 3.0.0 it is changed to
                type: string
                minLength: 1

I think it is a mistake and it should be changed back to
          type: integer
          minimum: 0

**Comment by globaltopmedia** [comment]
Is it just me, but if you set minimum:0 you exclude negative values
https://swagger.io/docs/specification/data-models/data-types/

**Comment by patricekrakow** [comment]
Done, see commit [4f7cb88](https://github.com/papinet/papiNet-API/commit/4f7cb8820b1c36631502186c62ad088587034180).
