### ISSUE TITLE
ListOfDeliveryNotes.deliveryNotes.shipmentStatus in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#133]
**The same issues also apply to DeliveryNoteById.shipmentStatus**

1 All parties might not implement GoodsReceipt. shipmentStatus should be changed to **optional** as decided at API meeting on 2025-02-28.

2 Current Enumerations
- Planned
- Departed
- Arrived

At API meeting on 2025-02-28 there was a decison to add enumeration **Loaded**.

In Stora use case the GoodsReceipt will be sent after unloading of the goods, i.e. not when it has arrived.
So enumeration **Unloaded** should be added.

Should papiNet keep enumeration **Arrived** or remove it?

If deliveryNoteStatus is Cancelled, what enumeration should then be used for shipmentStatus?
Should papiNet add a new enumeration **Cancelled** to be used in this case?

**Comment by patricekrakow** [comment]
- We keep the "Arrived" enumeration value.
- We add the "Cancelled" enumeration value, which has a different meaning than the "Cancelled" of the `deliveryNoteStatus`.

**Comment by patricekrakow** [comment]
Done, see commit [9c746e3](https://github.com/papinet/papiNet-API/commit/9c746e330b4a8ad845eb53ecf3f8047a94bf0d3a).
