### ISSUE TITLE
GetDeliveryNoteById.transport in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#134]
There is currently no identifier of the transport unit.
I suppose that the receiver of the goods also need an identifier of the transport unit to know which DeliveryNote belongs to which transport unit.

Wouldn't also an identifier of the vehicle be needed as well as a vehicleType?
For example, a road transport is coming with 3 containers loaded on 2 transport units. There is a Delivery Note for each container. Transport unit no 1 is loaded with 1 container and transport unit 2 is loaded with 2 containers.
Shouldn't it be possible to see in the Delivery Note which transport unit is carrying the container?
We discussed this case at an API meeting and I think we decided that support for this case should be added. It is missing now.
I sent as agreed an xml example to Patrice for how it is handled in papiNet xml.

In supplier-order and in papiNet DeliveryMessage there is possibility to specify several delivery legs with transport info but not in the delivery-note.
Why this difference?

**Comment by patricekrakow** [comment]
The `transport` has been updated, see commit [c0b924e](https://github.com/papinet/papiNet-API/commit/c0b924eb74e25e72d97c191d4bf054d374dfd90f).
