### ISSUE TITLE
GetDeliveryNoteById.deliveryNoteLineItems.deliveryNoteLineItemStatus in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#135]
deliveryNoteLineItemStatus should be removed.

Having in the header
        deliveryNoteStatus:
          type: string
          enum:
            - Original
            - Replaced
            - Cancelled

means that the the whole delivery-note will be Replaced of Cancelled, i.e. no status is needed on line item.

**Comment by patricekrakow** [comment]
Done, see commit [0175430](https://github.com/papinet/papiNet-API/commit/0175430c20f07b365a41f13a1b21685d8a760450).
