### ISSUE TITLE
GetDeliveryNoteById.deliveryNoteLineItems required items in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#136]
purchaseOrderNumber and purchaseOrderLineItemNumber should be changed to optional.
Goods can be shipped without having any purchaseOrderNumber and purchaseOrderLineItemNumber.

sellerproduct should be changed to optional.
StoraEnso is not specifying the sellerProduct.

**Comment by patricekrakow** [comment]
The property `sellerProduct` within `deliveryNoteLineItems[]` was already not required.

Done, see commit [f500b38](https://github.com/papinet/papiNet-API/commit/f500b38a9be4435cb55718b8362429c6bf536e4a).
