### ISSUE TITLE
GetDeliveryNoteById.deliveryNoteLineItems.quantities in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#137]
1 **quantityContext:** 
Enumerations **Ordered** and **Confirmed** should be removed.

Add enumerations **Loaded**, **Planned** and **Shipped**.

**Loaded** to be used when shipmentStatus is **Loaded**. 
**Planned** to be used when shipmentStatus is **Planned**.
**Shipped** to be used when shipmentStatus is **Departed**.
**Shipped** to be used when shipmentStatus is **Arrived**.
**Shipped** to be used when shipmentStatus is **Unloaded**.

**N.B.** These changes of enumerations of **quantityContext:** apply also to packages.quantities

2 **quantityUom:**
When quantityType: is **Count** then enumerations of **quantityUom:**  should include all package types.
Add  enumeration **ReelPackage**
Rename enumeration **PalletUnit** to **Pallet** to be the same name as in package type.
Is enumeration **Package** needed? Used for ReelPackage in papiNet xml. Could maybe be used when an unspecified package type is specified in a quantityType: Count.
I think enumerations **Piece** and **ThousandPieces** are not applicable to paper and pulp use cases.

**N.B.** Applicable enumerations of **quantityUom:** in packages are not completely the same as in deliveryNoteLineItems.
For example, if package type is **Pallet* then quantityType: **Count** value:1 quantityUom: **Pallet** is not applicable.
I think that **PackageType** should be removed from enumerations of **quantityUom:** in packages.
Should non applicable enumerations be removed as earlier agreed?

**Comment by patricekrakow** [comment]
I will start with

- Add enumerations Loaded, Planned and Shipped.

**Comment by patricekrakow** [comment]
The update of `quantityContext` has been done, see commit [c542665](https://github.com/papinet/papiNet-API/commit/c542665229eb4ea76a4ecac668adf193a4403de1).

It is not possible to condition the enumeration values of `quantityUom` based on `quantityType` having a certain value.

**Comment by patricekrakow** [comment]
We should create a new issue about the enumeration values of `quantityUom`.

**Comment by patricekrakow** [comment]
[TO BE REVIEWED]

There are currently (2024-08-13) **27 occurrences** of `uom:`

> This list has been generated by `/tools/analyse-uom.js`.

- `.Paper.basisWeight.uom`:
  - `GramsPerSquareMeter`
  - `Pound`
- `.Paper.bulk.uom`:
  - `CubicCentimeterPerGram`
- `.Paper.caliper.uom`:
  - `Micron`
  - `Millimeter`
- `.Paper.recycledContent.uom`:
  - `Percentage`
- `.Paper.width.uom`:
  - `Centimeter`
  - `Inch`
  - `Millimeter`
- `.Paper.length.uom`:
  - `Centimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.Paper.reelDiameter.uom`:
  - `Centimeter`
  - `Inch`
  - `Millimeter`
- `.Paper.coreDiameterInside.uom`:
  - `Centimeter`
  - `Inch`
  - `Millimeter`
- `.SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.length.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Kilometer`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.width.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Kilometer`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.height.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Kilometer`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.weight.uom`:
  - `Gram`
  - `HundredPounds`
  - `Kilogram`
  - `MetricTon`
  - `Pound`
  - `ShortTon`
- `.SupplierOrderById.lineItems[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Kilometer`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `Package`
  - `PalletUnit`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `Skid`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `.LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.length.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Kilometer`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.width.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Kilometer`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.height.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Kilometer`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.weight.uom`:
  - `Gram`
  - `HundredPounds`
  - `Kilogram`
  - `MetricTon`
  - `Pound`
  - `ShortTon`
- `.LogisticsDeliveryNoteById.lineItems[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Kilometer`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `Package`
  - `PalletUnit`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `Skid`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `.LogisticsDeliveryNoteById.lineItems[].packages[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Kilometer`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `Package`
  - `PalletUnit`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `Skid`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `.LogisticsGoodsReceiptById.lineItems[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Kilometer`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `Package`
  - `PalletUnit`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `Skid`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `.LogisticsGoodsReceiptById.lineItems[].packages[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Kilometer`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `Package`
  - `PalletUnit`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `Skid`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `.DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.length.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Kilometer`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.width.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Kilometer`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.height.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Kilometer`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `.DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.weight.uom`:
  - `Gram`
  - `HundredPounds`
  - `Kilogram`
  - `MetricTon`
  - `Pound`
  - `ShortTon`
- `.DeliveryInstructionById.sequences[].lineItems[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Kilometer`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `Package`
  - `PalletUnit`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `Skid`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `.DeliveryInstructionById.sequences[].lineItems[].packages[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Kilometer`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `Package`
  - `PalletUnit`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `Skid`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`

**Comment by patricekrakow** [comment]
For the `.*.packages[].quantities[].uom`, we should remove `Package` from the enumeration.

**Comment by larsolofsson** [comment]
My proposal for changes

.SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.length.uom:
Remove Kilometer 

.SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.width.uom:
Remove Kilometer

.SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.height.uom:
Remove Kilometer

.SupplierOrderById.lineItems[].quantities[].uom:
Kilometer
Rename Package to ReelPackage
Rename PalletUnit to Pallet

.LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.length.uom:
Remove Kilometer

.LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.width.uom:
Remove Kilometer

.LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.height.uom:
Remove Kilometer

.LogisticsDeliveryNoteById.lineItems[].quantities[].uom:
Rename Package to ReelPackage
Rename PalletUnit to Pallet

.LogisticsDeliveryNoteById.lineItems[].packages[].quantities[].uom:
Rename Package to ReelPackage
Rename PalletUnit to Pallet
Remove PulpUnit

.LogisticsGoodsReceiptById.lineItems[].quantities[].uom:
Rename Package to ReelPackage
Rename PalletUnit to Pallet

.LogisticsGoodsReceiptById.lineItems[].packages[].quantities[].uom:
Rename Package to ReelPackage
Rename PalletUnit to Pallet
Remove PulpUnit

.DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.length.uom:
Remove Kilometer

.DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.width.uom:
Remove Kilometer

.DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.height.uom:
Remove Kilometer

.DeliveryInstructionById.sequences[].lineItems[].quantities[].uom:
Rename Package to ReelPackage
Rename PalletUnit to Pallet

.DeliveryInstructionById.sequences[].lineItems[].packages[].quantities[].uom:
Rename Package to ReelPackage
Rename PalletUnit to Pallet
Remove PulpUnit

**Comment by patricekrakow** [comment]
@larsolofsson let me know if there is a particular reason for not removing `Kilometer` from:
- `LogisticsDeliveryNoteById.lineItems[].quantities[].uom`
- `LogisticsDeliveryNoteById.lineItems[].packages[].quantities[].uom`
- `LogisticsGoodsReceiptById.lineItems[].quantities[].uom`
- `LogisticsGoodsReceiptById.lineItems[].packages[].quantities[].uom`
- `DeliveryInstructionById.sequences[].lineItems[].quantities[].uom`
- `DeliveryInstructionById.sequences[].lineItems[].packages[].quantities[].uom`

Otherwise, I will also remove these 6 additional occurrences of `Kilometer` value.

**Comment by patricekrakow** [comment]
@larsolofsson within the `*.lineItems[].packages[].quantities[].uom` we decided ([see the comment above](https://github.com/papinet/papiNet-API/issues/137#issuecomment-2288229587)) to completely remove the `PalletUnit` value (instead of renaming it to `Pallet`) as `Pallet` is the top level of any packaging.

For the `*.lineItems[].quantities[].uom`, I will rename `PalletUnit` to `Pallet` as per your comment above.

**Comment by patricekrakow** [comment]
Done, see commit [4f9608c](https://github.com/papinet/papiNet-API/commit/4f9608c3c3bc85f5f68bdebaa36a0ef325eaf12d).

- Remove `Skid` everywhere (7/7 occurences)

- Remove `Kilometer` (16/16 occurences) in
  - `SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.length.uom`
  - `SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.width.uom`
  - `SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.height.uom`
  - `SupplierOrderById.lineItems[].quantities[].uom`
  - `LogisticsDelievryNoteById.deliveryLegs[].transport.units[].measurements.length.uom`
  - `LogisticsDelievryNoteById.deliveryLegs[].transport.units[].measurements.width.uom`
  - `LogisticsDelievryNoteById.deliveryLegs[].transport.units[].measurements.height.uom`
  - `LogisticsDelievryNoteById.lineItems[].quantities[].uom`
  - `LogisticsDelievryNoteById.lineItems[].packages[].quantities[].uom`
  - `LogisticsGoodsReceiptById.lineItems[].quantities[].uom`
  - `LogisticsGoodsReceiptById.lineItems[].packages[].quantities[].uom`
  - `DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.length.uom`
  - `DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.width.uom`
  - `DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.height.uom`
  - `DeliveryInstructionById.sequences[].lineItems[].quantities[].uom`
  - `DeliveryInstructionById.sequences[].lineItems[].packages[].quantities[].uom`

- Rename `Package` (7/10 occurences) to `ReelPackage` in
  - `SupplierOrderById.lineItems[].quantities[].uom`
  - `LogisticsDeliveryNoteById.lineItems[].quantities[].uom`
  - `LogisticsDeliveryNoteById.lineItems[].packages[].quantities[].uom`
  - `LogisticsGoodsReceiptById.lineItems[].quantities[].uom`
  - `LogisticsGoodsReceiptById.lineItems[].packages[].quantities[].uom`
  - `DeliveryInstructionById.sequences[].lineItems[].quantities[].uom`
  - `DeliveryInstructionById.sequences[].lineItems[].packages[].quantities[].uom`

REMARK: The value `ReelPackage` also appears in `.packages[].type`, but the list is different for `LogisticsGoodsReceiptById` compared to `LogisticsDeliveryNoteById` and `DeliveryInstructionById`.

- Rename `PalletUnit` (4/7 occurences) to `Pallet` in
  - `SupplierOrderById.lineItems[].quantities[].uom`
  - `LogisticsDelievryNoteById.lineItems[].quantities[].uom`
  - `LogisticsGoodsReceiptById.lineItems[].quantities[].uom`
  - `DeliveryInstructionById.sequences[].lineItems[].quantities[].uom`

- Remove `PalletUnit` (3/7 occurences) in
  - `LogisticsDelievryNoteById.lineItems[].packages[].quantities[].uom`
  - `LogisticsGoodsReceiptById.lineItems[].packages[].quantities[].uom`
  - `DeliveryInstructionById.sequences[].lineItems[].packages[].quantities[].uom`

- Remove `PulpUnit` (3/10 occurences) in
  - `LogisticsDelievryNoteById.lineItems[].packages[].quantities[].uom`
  - `LogisticsGoodsReceiptById.lineItems[].packages[].quantities[].uom`
  - `DeliveryInstructionById.sequences[].lineItems[].packages[].quantities[].uom`

**Comment by patricekrakow** [comment]
Here is an updated output (with a fix for the preceding dot) from `tools/analyse-uom.js`:

- `Paper.basisWeight.uom`:
  - `GramsPerSquareMeter`
  - `Pound`
- `Paper.bulk.uom`:
  - `CubicCentimeterPerGram`
- `Paper.caliper.uom`:
  - `Micron`
  - `Millimeter`
- `Paper.recycledContent.uom`:
  - `Percentage`
- `Paper.width.uom`:
  - `Centimeter`
  - `Inch`
  - `Millimeter`
- `Paper.length.uom`:
  - `Centimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `Paper.reelDiameter.uom`:
  - `Centimeter`
  - `Inch`
  - `Millimeter`
- `Paper.coreDiameterInside.uom`:
  - `Centimeter`
  - `Inch`
  - `Millimeter`
- `SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.length.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.width.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.height.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `SupplierOrderById.lineItems[].deliveryLegs[].transport.units[].measurements.weight.uom`:
  - `Gram`
  - `HundredPounds`
  - `Kilogram`
  - `MetricTon`
  - `Pound`
  - `ShortTon`
- `SupplierOrderById.lineItems[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `ReelPackage`
  - `Pallet`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.length.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.width.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.height.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `LogisticsDeliveryNoteById.deliveryLegs[].transport.units[].measurements.weight.uom`:
  - `Gram`
  - `HundredPounds`
  - `Kilogram`
  - `MetricTon`
  - `Pound`
  - `ShortTon`
- `LogisticsDeliveryNoteById.lineItems[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `ReelPackage`
  - `Pallet`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `LogisticsDeliveryNoteById.lineItems[].packages[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `ReelPackage`
  - `Piece`
  - `Pound`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `LogisticsGoodsReceiptById.lineItems[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `ReelPackage`
  - `Pallet`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `LogisticsGoodsReceiptById.lineItems[].packages[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `ReelPackage`
  - `Piece`
  - `Pound`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.length.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.width.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.height.uom`:
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Inch`
  - `Meter`
  - `Millimeter`
  - `Yard`
- `DeliveryInstructionById.sequences[].deliveryLegs[].transport.units[].measurements.weight.uom`:
  - `Gram`
  - `HundredPounds`
  - `Kilogram`
  - `MetricTon`
  - `Pound`
  - `ShortTon`
- `DeliveryInstructionById.sequences[].lineItems[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `ReelPackage`
  - `Pallet`
  - `Piece`
  - `Pound`
  - `PulpUnit`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`
- `DeliveryInstructionById.sequences[].lineItems[].packages[].quantities[].uom`:
  - `Bale`
  - `Box`
  - `Centimeter`
  - `Decimeter`
  - `Foot`
  - `Gram`
  - `HundredPounds`
  - `Inch`
  - `Kilogram`
  - `Meter`
  - `MetricTon`
  - `Millimeter`
  - `ReelPackage`
  - `Piece`
  - `Pound`
  - `Ream`
  - `Reel`
  - `Sheet`
  - `ShortTon`
  - `SquareDecimeter`
  - `SquareFoot`
  - `SquareInch`
  - `SquareMeter`
  - `ThousandPieces`
  - `ThousandSquareCentimeters`
  - `ThousandSquareFeet`
  - `ThousandSquareInches`
  - `Yard`

**Comment by patricekrakow** [comment]
@larsolofsson, @bengtwentus, please confirm that I can close this issue based on commit [4f9608c](https://github.com/papinet/papiNet-API/commit/4f9608c3c3bc85f5f68bdebaa36a0ef325eaf12d).

**Comment by larsolofsson** [comment]
I removed uom Kilometer only for units.measurents
The length of paper on other places might be many kilometers.

**Comment by larsolofsson** [comment]
Patrice,

I removed uom Kilometer only for units.measurents

The length of paper on other places might be many kilometers.

 

 

Kind regards

Lars

**Comment by larsolofsson** [comment]
Patrice,
OK, my mistake.

 

Kind regards

Lars

**Comment by patricekrakow** [comment]
OK, I will put back the `Kilometer` where needed 👍

**Comment by patricekrakow** [comment]
Done, see commit [6d2e06a](https://github.com/papinet/papiNet-API/commit/6d2e06a33217f463911acaa1eeea9088b07f4539).
