### ISSUE TITLE
GetDeliveryNoteById.deliveryNoteLineItems.packages in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#138]
pacakages: is misspelt. Should be packages.

But as I see in the meeting notes 2024-02-28, there is a decision to name it as **deliveryNotePackages*
(goodsReceiptPackages in Goods Receipt).

**Extract from meeting notes:**
[OPTION 1]
deliveryNoteLineItems[].packages[]
goodsReceiptLineItems[].packages[]

[OPTION 2]
deliveryNoteLineItems[].packages[]
goodsReceiptLineItems[].goodReceiptPackages[]

[OPTION 3]
deliveryNoteLineItems[].deliveryNotePackages[]
goodsReceiptLineItems[].goodReceiptPackages[]

If we have to show both information in 1 message, OPTION 2 & 3, with different prefixes are better.

{
  packages: [ ... ]
  packages: [ ... ]
}
You cannot easily differentiate the `quantities` between delivery note(s) and good receipt(s)

vs.

{
  deliveryNotePackages: [ ... ]
  goodReceiptPackages: [ ... ]
}
You can directly differentiate the `quantities` between delivery note(s) and good receipt(s)

The package is the same, the package identifiers are the same, BUT the quantities CAN be different between the delivery note(s) and good receipt(s).

(14:51) BACK to Planning

{DECISION}
OPTION 3
{/DECISION}

**Comment by patricekrakow** [comment]
Done, I just need to refer to the commit.
