### ISSUE TITLE
GetDeliveryNoteById.deliveryNoteLineItems.packages.type in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#139]
Currently
                    type:
                      type: string
                      enum:
                        - ReelPackage
                        - Pallet
                        - PulpUnit

Add enumerations **Bale** and **Box** as in papiNet xml.

**Comment by patricekrakow** [comment]
Done, see commit [d8aec71](https://github.com/papinet/papiNet-API/commit/d8aec7134b41cb5743a8fbe4dd80e9af18161672).
