### ISSUE TITLE
GetDeliveryNoteById.deliveryNoteLineItems.deliveryNotePackages.packageIdentifiers in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#140]
1 **type:**
Add enumeration **Primary**

2 **codeType:**
Add enumerations **IFRA** and **Supplier**

**Comment by patricekrakow** [comment]
I will start with the following:

```text
type:
- Barcode
- RFTag
- Number
- QRCode

role:
- Primary
- Secondary

codeType:
- IFRA
- NARI
- UIC14
- UIC16
```

**Comment by patricekrakow** [comment]
Done, see commit [f054b46](https://github.com/papinet/papiNet-API/commit/f054b465e460539efc866aa47b7d6473125dbfdb).

I have also updated `CreateGoodsReceipt` accordingly.
