### ISSUE TITLE
ListOfLogisticsDeliveryNotes: and LogisticsDeliveryNoteById: in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#157]
shipFromLocation and shipToLocation exist in ListOfLogisticsDeliveryNotes:, but in LogisticsDeliveryNoteById: shipFromLocation and shipToLocation are in deliveryLegs:
There might be several deliveryLegs.
This is confusing. Which shipFromLocation and shipToLocation are in ListOfLogisticsDeliveryNotes:?

In ListOfLogisticsDeliveryNotes shipFromLocation would be shipFromLocation in the first deliveryLeg and shipToLocation would be shipToLocation in the last deliveryLeg.

In papiNet XML there is the same structure with "header" and delivery legs. But property names are different in "header" and delivery legs because they are not the same properties. In the "header" there is ShipToCharacteristics, the last ship to location. In delivery legs there are DeliveryOrigin (ship from location for the leg) and DeliveryDestination (ship to location for the leg).

I propose that shipFromLocation and shipToLocation are added to the "header" and that  shipFromLocation and shipToLocation in delivery leg are renamed to loadingLocation and unloadingLocation.

In XML shipFromParty and shipToParty are supplied in the "header" and not in the delivery legs. 
Shouldn't shipFromParty and shipToParty be moved from delivery leg to the "header"?

In XML there is a CarrierParty in the delivery leg.
Why is in API instead a mainCarrierParty in the delivery leg?
Should mainCarrierParty: be moved from delivery leg to "header" level?
Isn't mainCarrierParty: responsible for all delivery legs?
Should papiNet also add a carrierParty to the delivery leg?

**Comment by patricekrakow** [comment]
We can use the file https://github.com/papinet/papiNet-API/blob/feature/supplier-order-3-0-0/3.0.0/logistics.xlsx to discuss this further.

**Comment by patricekrakow** [comment]
As decided during our 2024-08-14 (Wed) papiNet CWG meeting, we will keep the following properties:
- `ListOfLogisticsDeliveryNotes.items[].shipFromLocation`
- `ListOfLogisticsDeliveryNotes.items[].shipToLocation`

But, we will respectively add the following description to them:
- It MUST correspond to the `.shipFromLocation` of the **first** `deliveryLegs[]`
- It MUST correspond to the `.shipToLocation` of the **last** `deliveryLegs[]`

**Comment by patricekrakow** [comment]
Done, see commit [849faf0](https://github.com/papinet/papiNet-API/commit/849faf033776f1f526386f594dfc4714ed05c7d3).

**Comment by patricekrakow** [comment]
We will also add the (missing) corresponding query parameters for filtering:
- `GET /logistics-delivery-notes?shipFromLocation.value={string}`
- `GET /logistics-delivery-notes?shipFromLocation.assignedBy={string}`
- `GET /logistics-delivery-notes?shipToLocation.value={string}`
- `GET /logistics-delivery-notes?shipToLocation.assignedBy={string}`

As well as the missing:
- `GET /logistics-delivery-notes?deliveryInstructionNumber={string}`
- `GET /logistics-delivery-notes?deliveryInstructionSequenceNumber={integer}`

**Comment by patricekrakow** [comment]
Done, see commit [98d6aa5](https://github.com/papinet/papiNet-API/commit/98d6aa5432668bb439e2437e2726cfb00a7e445f).

**Comment by larsolofsson** [comment]
Patrice,

I think we decided to add 

*	ListOfLogisticsDeliveryNotes.items[].shipFromLocation
*	ListOfLogisticsDeliveryNotes.items[].shipToLocation

But after that we decided to only add them as Parameters for filtering, i.e. not as separate properties

 

 

Kind regards

Lars

**Comment by larsolofsson** [comment]
Patrice,

I forgot, they are needed if filtering is not used.

 

 

Kind regards

Lars
