### ISSUE TITLE
ListOfDeliveryInstructions: and DeliveryInstructionById: in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#158]
Similar issues as in issue #157

Additional issue
1. I think that it should be possible to filter on shipFromLocation and ShipToLocation when requesting a ListOfDeliveryInstructions. These properties are missing in ListOfDeliveryInstructions: .
How would this be designed when the sequence is an array?

**Comment by patricekrakow** [comment]
We can use the file https://github.com/papinet/papiNet-API/blob/feature/supplier-order-3-0-0/3.0.0/logistics.xlsx to discuss this further.

**Comment by patricekrakow** [comment]
It is not possible to add the properties `shipFromLocation` and/or `shipToLocation` within the `ListOfDeliveryInstructions` schema as a single _delivery instruction_ may have multiple _ship-from locations_ and/or _ship-to locations_.

However, it does make sense to filter the `ListOfDeliveryInstructions` based on `shipFromLocation` and/or `shipToLocation` so we will add them as query parameters:

**Comment by patricekrakow** [comment]
Done, see commit [84ec010](https://github.com/papinet/papiNet-API/commit/84ec01031b2383c68b8b3633a8c4881846c6ed52).
