### ISSUE TITLE
Many suppliers in a corporate group having a common domain.

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#159]
supplierParty was added to supplierOrder endpoints because a corporate group can use a common domain for many supplier parties.

supplierParty is missing in several logistics endpoints. Shouldn't supplierParty be added to these endpoints for the same reason as for the supplierOrder.
It should also be possible to filter on supplierParty when requesting a list of items.

**Comment by patricekrakow** [comment]
We can use the file https://github.com/papinet/papiNet-API/blob/feature/supplier-order-3-0-0/3.0.0/logistics.xlsx to discuss this further.

**Comment by patricekrakow** [comment]
During our 2024-08-14 (Wed) papiNet CWG meeting, we have decided to
- Add `supplierParty` into
  - `ListOfLogisticsDeliveryNotes.items[]`
  - `LogisticsDeliveryNotes`
- Add `logisticsSupplierParty` into
  - `ListOfSupplierOrders.items[]`
  - `SupplierOrderById`
  - `ListOfLogisticsDeliveryNotes.items[]`
  - `LogisticsDeliveryNotes`
  - `DeliveryInstructionById.sequences[]`

**Comment by patricekrakow** [comment]
The file <https://github.com/papinet/papiNet-API/blob/feature/supplier-order-3-0-0/3.0.0/logistics.xlsx> has been updated accordingly, see commit [2e46c71](https://github.com/papinet/papiNet-API/commit/2e46c71b4b68865439853acc5bec0162c6cbcd5b).

**Comment by patricekrakow** [comment]
Done, see commit [9833e4b](https://github.com/papinet/papiNet-API/commit/9833e4bf122f2413f547beafa9f2c7634d5e43e1).

**Comment by patricekrakow** [comment]
I missed adding the `logistisSupplierParty` as a query parameter for filtering.

**Comment by patricekrakow** [comment]
Done, see commit [d998c63](https://github.com/papinet/papiNet-API/commit/d998c6343723ad5794773693850e3331a9027f3b).
