### ISSUE TITLE
transports.units[] in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#161]
1. Enum missing for type: in transports.units,identifier.
Enum to be added: ContainerID, CassetteID, GlobalIndividualAssetIdentifier, GlobalReturnableAssetIdentifier, LicencePlateNumber, RailCarID, RFTagSerialNumber, SerialShippingContainerCode, TrailerID and VesselUnitID.
N.B. Some enumerations in papiNet XML related to FWS&B user group are not added.

2. transports.units,unitReferences
Replace existing properties with:
transportUnitLevel (Required, same  as units.level)
transportUnitType (Required, same as units.type)
transportUnitIdentifier (Required, same as units.identifier)

3. N.B. In supplierOrder and deliveryInstruction are identifier and unitreferences in transports.units not known.
papiNet has decided to have locally defined items with only applicable properties according to the context.
Should  identifier and unitreferences in transports.units be removed in supplierOrder and deliveryInstruction?

**Comment by patricekrakow** [comment]
1. To be done (remove some enumeration values).
2. I have only replicate the properties of `units[].identifier`, not the whole `unit[]`... (to be discussed)
3. (to be discussed)

**Comment by patricekrakow** [comment]
To be merged with Issue #144.

**Comment by patricekrakow** [comment]
1. and 2. have been done in commit [37c311f](https://github.com/papinet/papiNet-API/commit/37c311f4bde7b93d004fd4978dbb6479aa098ebd).
3. Let's discuss during our next papiNet CWG meeting, see notes above.

**Comment by patricekrakow** [comment]
Discussing during papiNet CWG meeting 2024-10-23 (Wed), it looks like `"value": "NotAllocated"` is "weird"... So, we need to re-discuss it during our next meeting while everyone will be there...

**Comment by patricekrakow** [comment]
Let's discuss this issue during our next papiNet CWG meeting on the 2024-11-06 (Wed).

**Comment by patricekrakow** [comment]
We will keep the schemas as they are, with the full `units[]` structure. We will simply remove the `units[]` from the instances in:
- `\3.0.0\mock\GW02&BW02.get-supplier-orders-supplierOrderId.response.json` (1 occurrence)
- `\3.0.0\paper-board-pulp-warehouse-logistics.md` (2 occurrences)
- `\3.0.0\mock\papiNet.PACT.json` (2 occurrences)

**Comment by patricekrakow** [comment]
Closed during papiNet CWG meeting 2024-11-20 (Wed).
