### ISSUE TITLE
 LogisticsGoodsReceiptById: quantities

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#163]
Enumerations for quantities.context in  LogisticsGoodsReceiptById should only be Shipped.
Remove enumerations Confirmed, Invoiced, Ordered and Produced.

**Comment by patricekrakow** [comment]
Done, see commit [611a38d](https://github.com/papinet/papiNet-API/commit/611a38d2052c3e9796840bbed614ad88d569ad29).
