### ISSUE TITLE
ListOfSupplierOrders: and SupplierOrderById: in version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#164]
Similar issues as #157

Additional issue

I think that it should be possible to filter on shipFromLocation and ShipToLocation when requesting a ListOfSupplierOrders. These properties are missing in ListOfSupplierOrders:

**Comment by patricekrakow** [comment]
We can use the file https://github.com/papinet/papiNet-API/blob/feature/supplier-order-3-0-0/3.0.0/logistics.xlsx to discuss this further.

**Comment by patricekrakow** [comment]
It is not possible to add the properties `shipFromLocation` and/or `shipToLocation` within the `ListOfSupplierOrders` schema as a single _supplier order_ may have multiple _ship-from locations_ and/or _ship-to locations_.

However, it does make sense to **filter** the `ListOfSupplierOrders` based on `shipFromLocation` and/or `shipToLocation` so we will add them as query parameters:

```
GET /supplier-orders?shipFromLocation={location(s)}
GET /supplier-orders?shipToLocation={location(s)}
```

**Comment by patricekrakow** [comment]
For consistency, as discussed during our 2024-15-14 (Wed) papiNet CWG meeting, we will also add the following query parameters:

```
GET /supplier-orders?sellerParty.value={sellerPartyValue}
GET /supplier-orders?sellerParty.assignedBy={sellerPartyAssignedBy}
GET /supplier-orders?supplierParty.value={supplierPartyValue}
GET /supplier-orders?supplierParty.assignedBy={supplierPartyAssignedBy}
GET /supplier-orders?customerParty.value={customerPartyValue}
GET /supplier-orders?customerParty.assignedBy={customerPartyAssignedBy}
GET /supplier-orders?buyerParty.value={buyerPartyValue}
GET /supplier-orders?buyerParty.assignedBy={buyerParty.assignedBy}
```

**Comment by patricekrakow** [comment]
Done, see commit [84ba6da](https://github.com/papinet/papiNet-API/commit/84ba6da0a17d618a9f0042fdca601a46819e010b).
