### ISSUE TITLE
supplier-order-3-0-0 GET listing functions dont support offset even though the description indicates so

### ISSUE THREAD

**Issue by globaltopmedia** [papinet/papiNet-API#171]
`  '/delivery-instructions':
    # GET /delivery-instructions
    # None => ListOfDeliveryInstructions
    get:
      summary: List `delivery-instructions`
      description: Get a **paginated** list of all `delivery-instructions`.`

see https://github.com/papinet/papiNet-API/blob/feature/supplier-order-3-0-0/3.0.0/papiNet-API.yaml

Paginated list is mentioned in the description.

**Comment by patricekrakow** [comment]
Indeed. Thanks! I have forgotten to add the `offset` and `limit` query parameters (as defined in release 2.0.0) for the list/collection API endpoints:

- `GET /supplier-orders`
- `GET GET /logistics-delivery-notes`
- `GET /delivery-instructions`

**Comment by patricekrakow** [comment]
Done, see commit [1846819](https://github.com/papinet/papiNet-API/commit/184681951bd3f4bd16478d51746ab5be75a93880).
