### ISSUE TITLE
Errors in Interaction 4 of Scenario A version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#179]
**SellerProduct**
Country code is missing for Classification, type ExportHarmonisedSystemCode.
Property countryCode is optional in schema, but required for Classification, type ExportHarmonisedSystemCode.

**"loadingCharacteristics"**
Currently: "text": "reels on end (cheese)"
Text shouldn't be used when dedicated codes exist in schema.
Change to: "type": - Standing

When unloading is from back of vehicle as specified in "unloadingCharacteristics", then should to "loadingCharacteristics" be added "labelOrientation" "type": - BackEndSide
The reel label has to face the unloading truck.

**Weight of packages**
BasisWeight = 370 GramsPerSquareMeter and Area = 3500 SquareMeter gives a package  net weight = 1295 Kilogram + the weight of the core. Values has to be adjusted to match.

**Update other interactions accordingly if the same errors exist for these properties.**

**Comment by patricekrakow** [comment]
I have added `countryCode: SE` the instance `\3.0.0\mock\GW04&BW04.get-logistic-delivery-notes-logisticDeliveryNoteId.response.json` in:
- `\3.0.0\paper-board-pulp-warehouse-logistics.md` (2 occurrences)
- `\3.0.0\mock\GW04&BW04.get-logistic-delivery-notes-logisticDeliveryNoteId.response.json` (1 occurrence)
- `\3.0.0\mock\papiNet.PACT.json` (2 occurrences)

**Comment by patricekrakow** [comment]
Partially one done, see commit [a9d735c](https://github.com/papinet/papiNet-API/commit/a9d735c0916be4c43398a0e57197078f8c4f0977).

**Comment by larsolofsson** [comment]
loadingCharacteristics is also used for specifying how to load packages so they can be unloaded easily and efficiently depending on which side of the transport unit they will be unloaded from.
If the packages will be unloaded from the rear side of the transport unit,  then "labelOrientation" "type": - BackEndSide specifies that. When unloading a package, the truck driver should be able to see the label on the package and the truck scanner should be able to read the bar code on the label.

unloadingCharacteristics is used for specifying how packages should be handled when unloaded, e.g. if the packages should be standing or lying after unloading.

**Comment by patricekrakow** [comment]
I should remove the `.loadingCharacteristics.text ` and add `"type": "Standing"` to the `.loadingCharacteristics` of:
- `\3.0.0\mock\BW08.get-delivery-instructions-deliveryInstructionId.response.json`
- `\3.0.0\mock\GW04&BW04.get-logistic-delivery-notes-logisticDeliveryNoteId.response.json`
- `\3.0.0\mock\GW07.get-delivery-instructions-deliveryInstructionId.response.json`

**Comment by patricekrakow** [comment]
So, I will replace the **11 occurrences** of

```json
{
  "loadingCharacteristics": [
    {
      "text": "reels on end (cheese)"
    }
  ]
}
```

with

```json
{
  "loadingCharacteristics": [
    {
      "type": "Standing",
      "labelOrientation": "BackEndSide"
    }
  ]
}
```

**Comment by patricekrakow** [comment]
Done, see commit [6d3cd5b](https://github.com/papinet/papiNet-API/commit/6d3cd5bd38d8084474892547fff8e8506d7afa51).

We can close this issue as we will finalize checking the consistency of the figures within issue https://github.com/papinet/papiNet-API/issues/189.

**Comment by patricekrakow** [comment]
Closed during papiNet CWG meeting 2024-11-20 (Wed).
