### ISSUE TITLE
Interaction 6  and 7 of Scenario A, version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#182]
Update description text for the interactions by replacing the text "open delivery instruction(s)" with "active delivery instruction(s)"

**Comment by patricekrakow** [comment]
Let's replace `open` by `active` in `\3.0.0\paper-board-pulp-warehouse-logistics.md` (4 occurrences).

**Comment by patricekrakow** [comment]
Done, see commit [8d4d104](https://github.com/papinet/papiNet-API/commit/8d4d104fb9b4e8cf37b9a10439bf3815e0861d13).

@larsolofsson please close this issue if you agree with the updates.
