### ISSUE TITLE
Quantity context is wrong in delivery notes with ShipmentStatus = Departed

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#183]
Change all quantity context = Loaded to be Shipped in delivery notes with ShipmentStatus = Departed.

Use of the context is outlined in the schema
  - Loaded  # when shipmentStatus = Loaded
   - Planned # when shipmentStatus = Planned
   - Shipped # when shipmentStatus = Arrived | Departed | Unloaded

Also in interaction description texts should Loaded be replaced by Shipped för delivery notes with ShipmentStatus = Departed.

**Comment by patricekrakow** [comment]
As the `shipmentStatus` is `Departed`, then all the `quantities[].context` should be `Shipped` in all instances.

**Comment by patricekrakow** [comment]
Let's make the following updates:

- within `3.0.0\mock\BW09.post-logistic-delivery-notes.request.json`, let's replace `"context": "Loaded"` with `"context": "Shipped"` (38 occurrences)

- within `3.0.0\mock\BW10.put-logistic-delivery-notes-logisticDeliveryNoteId.request.json`, let's replace `"context": "Loaded"` with `"context": "Shipped"` (38 occurrences)

- within `3.0.0\mock\GW04&BW04.get-logistic-delivery-notes-logisticDeliveryNoteId.response.json`, let's replace `"context": "Loaded"` with `"context": "Shipped"` (42 occurrences)

- within `3.0.0\mock\GW08.post-logistic-delivery-notes.request.json`, let's replace `"context": "Loaded"` with `"context": "Shipped"` (42 occurrences)

- within `3.0.0\paper-board-pulp-warehouse-logistics.md`, let's update:
  - `BW09.post-logistic-delivery-notes.request.json`
  - `BW10.put-logistic-delivery-notes-logisticDeliveryNoteId.request.json`
  - `GW04&BW04.get-logistic-delivery-notes-logisticDeliveryNoteId.response.json`
  - `GW08.post-logistic-delivery-notes.request.json`

- within `3.0.0\mock\papiNet.PACT.json`, let's update:
  - `"description": "Interaction 4 of Scenario A"`
  - `"description": "Interaction 4 of Scenario B"`

**Comment by patricekrakow** [comment]
Done, see commit [239bda5](https://github.com/papinet/papiNet-API/commit/239bda59a3740ef4a376cd6782da4a7ba5dc86c1).

**Comment by patricekrakow** [comment]
Closed during papiNet CWG meeting 2024-11-20 (Wed).
