### ISSUE TITLE
assignedBy in safetyAndEnvironmentDetails, version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#184]
assignedBy in safetyAndEnvironmentDetails is now required in the schema.
In papiNet XML it is optional because it is not needed for some enumerations of safetyAndEnvironmentalType.

I propose to make assignedBy optional in safetyAndEnvironmentDetails.to make it possible in the future to add new types not having any assignedBy.

Currently in papiNet API, Deforestation needs assignedBy EU, but various types for FSC an PEFC don't need any assignedBy, because the name and the definition of the type enumeration specifies fully what it is.

**Comment by patricekrakow** [comment]
OK, let's make the `assignedBy` not required within the `safetyAndEnvironmentDetails` (2 occurrences).

**Comment by patricekrakow** [comment]
Done, see commit [044fd67](https://github.com/papinet/papiNet-API/commit/044fd67fe0136b0211b8df5e58830931f2ef3d90).

@larsolofsson please close this issue if you agree with the updates.
