### ISSUE TITLE
Property status in LogisticsGoodsReceiptById, version 3.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#187]
Enumeration Cancelled is missing for property status in LogisticsGoodsReceiptById.

GoodsReceiptStatusType in papiNet xml has the following enumerations
- Cancelled
- Original
- Replaced

**Comment by patricekrakow** [comment]
OK, let's add the `enum` (enumeration) value `Cancelled` to `LogisticsGoodsReceiptById.status`.

**Comment by patricekrakow** [comment]
Done, see commit [f1ce32f](https://github.com/papinet/papiNet-API/commit/f1ce32ff3037fd068b6cae0fefd2e4df5e868ece).

@larsolofsson please close this issue if you agree with the updates.

**Comment by patricekrakow** [comment]
However, this will be overwritten later by the result of issue #177.
