### ISSUE TITLE
Document what items are required in use case

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#37]
We need to document what items are required in papiNet use cases to guide all parties to implement papiNet API in the same way.

**Comment by patricekrakow** [comment]
Add

```yaml
required:
  - quantityContext
  - quantityType
  - quantityValue
  - quantityUOM
```

in the quantity construct of
[V] quantities within CheckAvailabilityOfSellerProductById
[V] plannedQuantities within CheckAvailabilityOfSellerProductById
[V] quantities within CheckAvailabilityOfCustomerArticleById
[V] plannedQuantities within CheckAvailabilityOfCustomerArticleById
[V] quantities within OrderLineItem

**Comment by patricekrakow** [comment]
Done, see https://github.com/papinet/papiNet-API/commit/576e514a58176fbb64018acfbd3f31ab40a78022
