### ISSUE TITLE
Use Case shipment-status Scenario C is not correct for Corp = Enduser

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#38]
The use case shipment-status states that an Enduser can track shipments but it doesn't work for a party having the business role  Enduser with the current design of the use case. It only works for parties having the business role Order_Issuer.
Extract from use case description:
**Process**
_The Order Issuer and/or the End User can track expected shipments, related to the orders, from the Supplier._

All instances of Enduser should be removed from the description of the use case.
Corp should have only one business role Order_Issuer.

An Printer can also issue orders but in that case the business role is Order_Issuer when requesting an order-status.

It is common the an Enduser such as a Printer, prints items for several Publishers.
Several Order Issuers might use the same Order Number.

The following references are not unique
"shipmentReferences": [
        {
          "type": "OrderNumber",
          "assignedBy": "OrderIssuer",
          "value": "ORD001"
        },
        {
          "type": "OrderLineItemNumber",
          "assignedBy": "OrderIssuer",
          "value": "1"
        }
      ],

**Comment by patricekrakow** [comment]
This will be fixed in the schema of 1.3.0. I still need to update the drawing, and remove the "End User" role. BTW, this time, I should include the source of the drawing ;-)

**Comment by patricekrakow** [comment]
Done, see https://github.com/papinet/papiNet-API/commit/17e4a5944e599ae706e04683553a0744a4aa3d4b
