### ISSUE TITLE
Catalogue Scenario C needs to be updated

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#41]
The process for scenario C needs to be clarified and updated. 
To request details for a seller-product or a customer_article an UUID is needed. Is this statement correct and agreed? i.e. papiNet always require a UUID to request information about an item. We have seen that other API implementations also use other identifiers, e.g. like papiNet otherIdentifier.

If the customer doesn't store the UUID in his business system, then a 2 step solution is needed to get the details, i.e. step 1 to get UUID using otherIdentifier and step 2 to get the details using UUID.

My proposal if the statement above is correct and agreed:

- The description of Scenario C should state that the customer doesn't store the UUID and that a 2 step solution is needed to get the details of a seller-product or a customer-article using the otherIdentifier.

- The descriptions of the steps in scenario C should also be updated to describe the 2 step solution.

We should also document our API design rules as have done for the papiNet XML standard.

**Comment by patricekrakow** [comment]
"Step 3 of Scenario C" is the starting of the "2-step solution" described above.

We have started to document our API design rules with the `papiNet-JSON-Style-Guide.md` file.
