### ISSUE TITLE
Property shipmentReferences in ShipmentHeader needs to be changed to required

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#49]
The client needs a shipment reference in ShipmentHeader to be able to detect what item the shipment belongs to, e.g. an order number.
Therefore property shipmentReferences in ShipmentHeader needs to be changed to required.

**Comment by patricekrakow** [comment]
The `shipmentReferences` property is an `array` so in addition to having it `required`, I guess you would also like to mention that it MUST contain at least one item. This last constraint is not yet possible with OpenAPI, but we agree to mention it as a comment for the time being as follow:

```yaml
# minContains: 1 (new in JSON Schema New in draft 2019-09, not supported yet by OpenAPI)
```

**Comment by patricekrakow** [comment]
That's agreed. @patricekrakow will include that change in a PR.

**Comment by patricekrakow** [comment]
Done within <https://github.com/papinet/papiNet-API/commit/4aecf37c6dd287e58f2a2b008a963fb788f476a3>.
