### ISSUE TITLE
Properties latitude and logitude in Event.location should be changed to required

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#50]
Both latitude and longitude are needed to specify the position of the location.

**Comment by patricekrakow** [comment]
I have kept the `latitude` and `longitude` properties optional on purpose. Only the `name` property is `required`. I have done it this way as the example within the "Interaction 3 of Scenario A" section of the "Availability Use Case" does contain a response with only a `name`.

```json
{
  "name": "Sappi Germany"
}
```
Let's discuss this issue during our next meeting (2022-07-27).

**Comment by patricekrakow** [comment]
I have just realized that I was talking about the `GetLocationById` schema component, while you did mention the `location` property within the `Event` schema component. We will need to align these two structures following our discussion during our next meeting (2022-07-27).
