### ISSUE TITLE
Properties estimatedAvailableDateTime and quantities in plannedQuantities should be changed to required.

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#51]
Property plannedQuantities  is optional in CheckAvailabilityOfSellerProductById and CheckAvailabilityOfCustomerArticleById. 
It doesn't make sense supplying plannedQuantities without also specifying properties estimatedAvailableDateTime and quantities.

Therefore should Properties estimatedAvailableDateTime and quantities in plannedQuantities be changed to required.

**Comment by patricekrakow** [comment]
Done within <https://github.com/papinet/papiNet-API/commit/a87eaac286d7e9bf3297cd9f10f844e4236068d8>.
