### ISSUE TITLE
Property quantityContext in CheckAvailabilityOfSellerProductById and CheckAvailabilityOfCustomerArticleById

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#52]
Shouldn't quantityContext be the same for quantities in both CheckAvailabilityOfSellerProductById and CheckAvailabilityOfCustomerArticleById?
Shouldn't quantityContext be the same for plannedQuantities in both CheckAvailabilityOfSellerProductById and CheckAvailabilityOfCustomerArticleById?

We need to discuss what enumerations are valid.

**Current enumerations**
CheckAvailabilityOfSellerProductById property quantities
enum: 
     - OnHand
     - Reserved
     - InTransit
       # PlannedProduction does not make sense in the context of 'plannedQuantities'
       _N.B. 'plannedQuantities' is not correct in this comment. My proposal is 'already produced quantities'._

CheckAvailabilityOfCustomerArticleById property quantities
enum:
      - OnHand
      - Reserved
       - InTransit
       - PlannedProduction

CheckAvailabilityOfSellerProductById property plannedQuantities
 enum:
      # OnHand does not make sense in the context of 'plannedQuantities'
      # Reserved does not make sense in the context of 'plannedQuantities'
      # InTransit does not make sense in the context of 'plannedQuantities'
       - PlannedProduction

CheckAvailabilityOfCustomerArticleById property plannedQuantities
enum:
     # OnHand does not make sense in the context of 'plannedQuantities'
      - Reserved
       - InTransit
       - PlannedProduction

**Comment by patricekrakow** [comment]
I do agree that they MUST be the same. This is a mistake, I would propose the following:

```text
CheckAvailabilityOfSellerProductById | CheckAvailabilityOfCustomerArticleById
  quantities
    quantityContext
      - OnHand
      - Reserved
      - InTransit
      # PlannedProduction does not make sense in the context of 'quantities'
  plannedQuantities
    quantities
      quantityContext
        # OnHand does not make sense in the context of 'plannedQuantities'
        # Reserved does not make sense in the context of 'plannedQuantities'
        # InTransit does not make sense in the context of 'plannedQuantities'
        - PlannedProduction
```

Let's discuss this issue during our next meeting (2022-07-27).

**Comment by patricekrakow** [comment]
Finally, we will implement the following:

```text
CheckAvailabilityOfSellerProductById | CheckAvailabilityOfCustomerArticleById
  quantities
    quantityContext
      - OnHand
      - Reserved
      # InTransit does not make sense in the context of 'quantities'
      # PlannedProduction does not make sense in the context of 'quantities'
  plannedQuantities
    quantities
      quantityContext
        # OnHand does not make sense in the context of 'plannedQuantities'
        # Reserved does not make sense in the context of 'plannedQuantities'
        - InTransit
        - PlannedProduction
 ```

**Comment by patricekrakow** [comment]
Done within #64.
