### ISSUE TITLE
catalogue.md Interaction 4 of Scenario B and C, Post: create a customer article

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#55]
"id" exists in the response example but is missing in the schema. 
"id": "fd345ee7-ba9a-4856-8fcb-a912b10ea971",
  "otherIdentifier": { "value": "SAP12345", "assignedBy": "Customer" },
  "sellerProductOtherIdentifier": {
    "value": "galerie-brite",
    "assignedBy": "Seller"

Schema
CreateCustomerArticle:
      type: object
      required:
        - name
      properties:
        otherIdentifier:
          type: object
          required:
            - value
          properties:
            value:

PUT /customer-articles/{customerArticleId}
PATCH /customer-articles/{customerArticleId}
The "id" is also missing in the schema for  responses to PUT and PATCH, but this might be OK because customerArticleId (uuid) exists in the request. Information in the request doesn't need to be included in the reponse. 
"id" in the request is in many other papiNet examples included in the response. 
Should we do this in a consistent way?

**Comment by patricekrakow** [comment]
The `id` property MUST be added to `GetLocationById` schema and the examples need to be updated accordingly.

As a general rule, I think we can say that the `id` MUST be included in a response body and MUST not be in a request body (as it is conveyed within the URL).

**Comment by patricekrakow** [comment]
Done within <https://github.com/papinet/papiNet-API/commit/889cc8ea5c91008c7e66415e6e15f0f9470b9ecc>.

**Comment by larsolofsson** [comment]
format: uuid is missing for property id in GetLocationByID:
