### ISSUE TITLE
Add a constraint that an empty array is not valid.

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#58]
In the current schema there is a comment about "minContains" to be added when supported by OpenAPI to make an empty array invalid, e.g.
shipments:
          type: array
          # minContains: 1 (new in JSON Schema New in draft 2019-09, not supported yet by OpenAPI)
          items:

"minContains" and "maxContains" can be used with "contains" to further specify how many times a schema matches a contains constraint. 

Shouldn't the constraint "minItems: 1" be used instead to make an empty array invalid in the above schema example?

**Comment by patricekrakow** [comment]
Yes, it's `minItems: 1` and not `minContains: 1`. And `minItems: 1` is **already** supported by OpenAPI :-) So, we should update all arrays.

**Comment by patricekrakow** [comment]
Done within <https://github.com/papinet/papiNet-API/commit/fca56fb79b30851fb9febc709c858f9565531032>.
