### ISSUE TITLE
“oneOf” for product types Paper, Pulp, etc

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#60]
Would the following construct be valid in a json schema to allow only for Paper or Pulp in a customer article?
I think it would also be good to specify the productType that is also communicated in ListCustomerArticles.

              productType:
                type: string
                enum:
                  - Paper
                  - Pulp

              oneOf:
                type: object
                required: paper
                  properties: 
                    paper:
                       $ref: '#/components/schemas/Paper'

                type: object
                required: pulp
                  properties: 
                    pulp:
                       $ref: '#/components/schemas/Pulp'

**Please also see attached email from Bengt.**
	
[Bengt's email, Re oneOf for Paper, Pulp etc.pdf](https://github.com/papinet/papiNet-API/files/9275302/Bengt.s.email.Re.oneOf.for.Paper.Pulp.etc.pdf)

**Comment by patricekrakow** [comment]
Yes! The `oneOf` is working as expected, see examples below...

We don't need to have the `productType`, it would be a bit redundant.

**Comment by patricekrakow** [comment]
The following example JSON schema shows how it works, it can be tested with <https://www.jsonschemavalidator.net/>:

```json
{
  "$schema": "http://json-schema.org/draft-00/schema#",
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "oneOf": [
    {
      "required": [ "paper"],
      "properties": {
        "paper": {
          "$ref": "#/Paper"
        }
      }
    },
    {
      "required": [ "pulp"],
      "properties": {
        "pulp": {
          "$ref": "#/Pulp"
        }
      }
    }
  ],
  "Paper": {
    "type": "object"
  },
  "Pulp": {
    "type": "object"
  }
}
```

**Comment by patricekrakow** [comment]
Fixed in https://github.com/papinet/papiNet-API/commit/7328d62b841083d679ce958e06f31df86b03162e.
