### ISSUE TITLE
Property status in ListSellerProducts: and GetSellerProductById:

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#61]
Why is Property "status" optional in ListSellerProducts: and GetSellerProductById:?
Property "status" is an important property specifying if the product is Active or Inactive.

Shouldn't it be required?

**Comment by patricekrakow** [comment]
It will be done if we approve the #66.

**Comment by patricekrakow** [comment]
Following the issue #66, it will be done. So, we can close this issue.
