### ISSUE TITLE
Property "status" in ListCustomerArticles:, GetCustomerArticleById: and CreateCustomerArticle:

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#62]
Why is Property "status" optional in ListCustomerArticles:, GetCustomerArticleById: and CreateCustomerArticle:?
Property "status" is an important property specifying if the Article is Active or Inactive.

Shouldn't it be required?

Property "sellerProductStatus" is also optional.
Shouldn't it also be required?

**Comment by patricekrakow** [comment]
It will be done if we approve the https://github.com/papinet/papiNet-API/issues/66.

**Comment by patricekrakow** [comment]
Following the issue https://github.com/papinet/papiNet-API/issues/66, it will be done. So, we can close this issue.
