### ISSUE TITLE
'/customer-articles/{customerArticleId}/check-availability':, description is wrong

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#63]
Current description is:
_description: UUID of the `seller-product` to check the `availability` for_
but it should be
_description: UUID of the `customer-article` to check the `availability` for_

**Please explain to me, why check-availability is a Post and not a Get.** 
There is no requestBody:, only an uuid as a parameter for sellerProductId or customerArticleId.

**Comment by patricekrakow** [comment]
Will correct it. Regarding the POST instead of a GET, see #68.

**Comment by patricekrakow** [comment]
Fixed in https://github.com/papinet/papiNet-API/commit/1d40025cbb0a706a2620331cd57d72120b101e31
