### ISSUE TITLE
papiNet-API.md quantityContext "InTransit" needs to be updated

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#64]
Currently
* _**InTransit**_: The quantity is shipped to a location.
 _**InTransit**_ should be changed to  _**InTransit**_

I propose an update of the definition
* _**InTransit**_: The quantity is transported to a stock location and has not yet arrived.

The definition of _**InTransit**_ should clearly be different to definition of _**Shipped**_
* _**Shipped**_: The quantity is shipped, it has left the _Supplier_'s location.

Does papiNet need to update definition of _**Shipped**_ ?
The quantity _**InTransit**_ is also shipped and has left a _Supplier_'s location

**Comment by patricekrakow** [comment]
It will be updated. Agreed with @larsolofsson and @robertalivan.

**Comment by patricekrakow** [comment]
Done within <https://github.com/papinet/papiNet-API/issues/64>.
