### ISSUE TITLE
availability.md, missing properties for the seller-product

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#65]
Properties for the seller-product is not the same as the properties for the same seller-product in the catalogue use case.
Some properties are missing in the availability use case. E.g. otherIdentifier, status, descriptions.

The schema for the product properties is the same for both the availability and the catalogue use cases.

Shouldn't the properties be the same for the same seller-product in both use cases?

**Comment by patricekrakow** [comment]
Closed. Replace by #71.
