### ISSUE TITLE
GetLocationById: issues

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#78]
**GetLocationById:** 
id: is missing format: uuid in the schema.

country in schema is just
country:
  type: string

"country": "BE", In Availability.md on line 409. 437 and 629
It should be "country": "Belgium" and not the country code when type: string

Should it be changed in the schema to countryCode:?
countryCode:
      type: string
      minLength: 1
     maxLength: 2
     description: The (two-letter) value - e.g. "SE", "BE", ... - MUST exist in the ISO 3166-1 standard list.

**Comment by patricekrakow** [comment]
Is has been fixed with https://github.com/papinet/papiNet-API/commit/040731a7f5e12d78f8ab2e51425155755104431e.
