### ISSUE TITLE
Wrong property names in PurchaseOrder 2.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#91]
supplierParty and sellerParty have wrong names in ListOfPurchaseOrders, CreatePurchaseOrder and     GetPurchaseOrderById.

supplierToParty to be changed to supplierParty.
sellerToParty to be changed to sellerParty.

**Comment by patricekrakow** [comment]
Strictly speaking we should make this change within a 3.0.0 version, changing property names is a n incompatible change. However, this is clearly a typo and I do not think that anyone has already created an implementation based on the current 2.0.0, so I would suggest that we just push this change in the current 2.0.0.

**Comment by patricekrakow** [comment]
We will go for 2.0.0 as a quick pragmatic exception, we should avoid doing that in the future!

**Comment by patricekrakow** [comment]
Changes have been implemented in PR #96.
