### ISSUE TITLE
Update latestAllowedDateTimeForChange in version 2.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#92]
minLength=4 is missing in schema for latestAllowedDateTimeForChange.

A description is missing for what local time is supplied in latestAllowedDateTimeForChange as decided at papiNet API meeting on 13 September 2023.

**Comment by patricekrakow** [comment]
The `"minLength": 4` is indeed missing, and I think it can be added directly to the 2.0.0 version. Someone who would have implemented 2.0.0 with a `latestAllowedDateTimeForChange` of less than 4 characters would be simply not correct.
Regarding the location of the local time, we do have the generic rule #10:

> The properties ending with the suffix "...DateTime" SHOULD contain a local date and time, in accordance with the ISO 8601 standard (and preferably using an explicit time zone offset) for which the location is defined by the business context.

**Comment by patricekrakow** [comment]
Done, see commit [08bbfa0](https://github.com/papinet/papiNet-API/commit/08bbfa057f2ad81d25a17941671506698a87c6db).
