### ISSUE TITLE
Adresses in version 2.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#94]
StateOrProvince and County are missing in addresses for parties and locations.

The state is important in US addresses.

Should papiNet set a max limit for number of name lines and address lines?

**Comment by patricekrakow** [comment]
In papiNet XML, the `state` and the `province` were merge into a single property such as `stateOrProvince`.

**Comment by patricekrakow** [comment]
I will add the two following non-required properties:

- `stateOrProvince`
- `county`

with the same semantics as in papiNet XML.

**Comment by patricekrakow** [comment]
Regarding the size limits of `nameLines` and `addressLines` arrays, we can use the same limits as in XML, 2 and 4.

**Comment by patricekrakow** [comment]
Change done in commit [8b05d10](https://github.com/papinet/papiNet-API/commit/8b05d1014cbde61366297b3741e29597593b4d65).

**Comment by patricekrakow** [comment]
Closed during papiNet CWG meeting 2024-01-17 (Wed).
