### ISSUE TITLE
namelines in in ListOfParties, version 2.0.0

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#98]
minLength should be changed from 2 to 1.

nameLines:
                type: array
                minItems: 1
                items:
                  type: string
                  minLength: 2

**Comment by patricekrakow** [comment]
Yes, this is clearly a typo in 1 of the occurrence of `nameLines` out of 4, I will fix it.

**Comment by patricekrakow** [comment]
Done, see commit [e1a22e3](https://github.com/papinet/papiNet-API/commit/e1a22e34f710e1bad42fb2f990c885a1d1025bc5).
