### ISSUE TITLE
agency used in colourShade and coreStrengthCode, version 2.0.0. agency vs assignedBy?

### ISSUE THREAD

**Issue by larsolofsson** [papinet/papiNet-API#99]
papiNet should be consistent when designing schemas.
In current work there are now both agency and assignedBy used with the same type of enumerations.
Either agency or assignedBy should be used, not both of them.

agency:
              type: string
              enum:
                - Buyer
                - Customer
                - EndUser
                - Seller
                - Supplier

**Comment by patricekrakow** [comment]
We decided to rename `agency` into `assignedBy`.

**Comment by patricekrakow** [comment]
Done, see commit [aeb0982](https://github.com/papinet/papiNet-API/commit/aeb0982df616b46f60316d4aea7539c2d55484c9).
